### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by cisnez** [dotmain/SynthesisFramework#1]
Line 10 in:
SynthesisFramework/Sources/SynthesisFramework/Synthesis/AudioSynthesis.swift

Xcode Warning: "Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead"

Suggest changing:
public protocol AudioSynthesisDelegate: class {
^^^ change to:
public protocol AudioSynthesisDelegate: AnyObject {

**Comment by dotmain** [comment]
hi, 

Much obliged for the suggestion. An update has been published. 

👏🏻
